5. pandas 시작하기

In [2]:
import pandas as pd

In [3]:
from pandas import Series, DataFrame

In [4]:
obj = pd.Series([4,7,-5,3])

obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([4,7,-5,3], index = ['d','b','a','c'])

obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [12]:
obj2[['c','a']]

c    3
a   -5
dtype: int64

In [13]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [15]:
import numpy as np
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2

True

In [17]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [18]:
states = ['California','Ohio','Oregon','Texas']

obj4 = pd.Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [19]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [21]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [23]:
obj4.name = 'population'

obj4.index.naem = 'state'

obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [24]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [26]:
obj.index = ["Bob",'Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

5.1.2 DataFrame

In [37]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)

frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [38]:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [39]:
frame2 = pd.DataFrame(data, columns=['year','state','pop','debt'],
                     index=['one','two','three','four','five','six'])

frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [40]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [41]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [42]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [43]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [44]:
frame2['debt']=np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [45]:
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

frame2['debt'] = val

frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [46]:
frame2['eastern'] = frame2.state == 'Ohio'

frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [48]:
del frame2['eastern']

frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [10]:
pop = {'Nevada':{2001:2.4,2002:2.9},
      'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [11]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [12]:
frame3 = pd.DataFrame(pop)

frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [13]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [53]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [55]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [54]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [57]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [58]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [59]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

5.1.3 색인 객체

In [3]:
import pandas as pd

obj = pd.Series(range(3),index = ['a','b','c'])

index = obj.index

index

Index(['a', 'b', 'c'], dtype='object')

In [4]:
index[1:]

Index(['b', 'c'], dtype='object')

In [6]:
index[1] = 'd' #색인 객체 변경 불가능

TypeError: Index does not support mutable operations

In [7]:
import numpy as np

labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [8]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [9]:
obj2.index is labels

True

In [14]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [15]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [16]:
'Ohio' in frame3.columns

True

In [17]:
2003 in frame3.index

False

In [19]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

색인 메서드: append, difference, intersection, union, isin, delete, drop, insert, is_monotonic, is_unique, unique

5.2 핵심 기능

5.2.1 재색인

In [20]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [21]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [22]:
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])

obj3

0      blue
2    purple
4    yellow
dtype: object

In [24]:
obj3.reindex(range(6),method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [26]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index=['a','c','d'],
                    columns = ['Ohio','Texas','California'])

frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [27]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [28]:
states = ['Texas','Utah','California']
frame3 = frame.reindex(columns = states)
frame3

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [29]:
frame.reindex(['a','b','c','d'],columns=states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

재색인 함수 인자:index, method, fill_value, limit, tolerance, level, copy

5.2.2 하나의 로우나 컬럼 삭제하기

In [31]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [32]:
obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [33]:
obj.drop(['b','c'])

a    0.0
d    3.0
e    4.0
dtype: float64

In [35]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['Ohio','Colordo','Utah','New York'],
                   columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colordo     4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [36]:
data.drop(['Ohio','Utah'])

one  two  three  four
Colordo     4    5      6     7
New York   12   13     14    15

In [37]:
data.drop(['two'],axis=1)

one  three  four
Ohio        0      2     3
Colordo     4      6     7
Utah        8     10    11
New York   12     14    15

In [39]:
data.drop(['three'],axis='columns')

one  two  four
Ohio        0    1     3
Colordo     4    5     7
Utah        8    9    11
New York   12   13    15

In [40]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [41]:
obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [42]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [43]:
obj.drop('c',inplace=True) #원본 삭제

In [44]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

5.2.3 색인하기, 선택하기, 거르기

In [45]:
obj = pd.Series(np.arange(4.), index = ['a','b','c','d'])
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [46]:
obj[['a','d']]

a    0.0
d    3.0
dtype: float64

In [47]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [48]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [49]:
data

one  two  three  four
Ohio        0    1      2     3
Colordo     4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [50]:
data['two']

Ohio         1
Colordo      5
Utah         9
New York    13
Name: two, dtype: int32

In [51]:
data[:2]

one  two  three  four
Ohio       0    1      2     3
Colordo    4    5      6     7

In [53]:
data[data['three']>5]

one  two  three  four
Colordo     4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [54]:
data <5

one    two  three   four
Ohio       True   True   True   True
Colordo    True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [57]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colordo     0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [59]:
data.loc['Colordo',['two','three']] #loc 축이름

two      5
three    6
Name: Colordo, dtype: int32

In [62]:
data.iloc[1,[1,2]] #iloc 정수 색인

two      5
three    6
Name: Colordo, dtype: int32

In [63]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colordo     7    0    5
Utah       11    8    9

In [65]:
data.loc[:'Colordo','two']

Ohio       0
Colordo    5
Name: two, dtype: int32

In [69]:
data.iloc[:,:3]

one  two  three
Ohio        0    0      0
Colordo     0    5      6
Utah        8    9     10
New York   12   13     14

In [67]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colordo     0    5      6
Utah        8    9     10
New York   12   13     14

5.2.4 정수 색인

In [74]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [79]:
ser[-1] # 정수기반 색인은 -1이 에러가 난다.

KeyError: -1

In [77]:
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [78]:
ser2[-1]

2.0

In [80]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [81]:
ser.iloc[:1]

0    0.0
dtype: float64

5.2.5 산술 연산과 데이터 정렬

In [82]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [86]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),
                  columns=list('bcd'),
                  index=['Ohio','Texas','Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),
                  columns=list('bce'),
                  index=['Utah','Ohio','Texas','Oregon'])

print(df1)
df2

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0


b     c     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [87]:
df1+df2

b     c   d   e
Colorado  NaN   NaN NaN NaN
Ohio      3.0   5.0 NaN NaN
Oregon    NaN   NaN NaN NaN
Texas     9.0  11.0 NaN NaN
Utah      NaN   NaN NaN NaN

In [88]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                  columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                  columns=list('abcde'))
df2.loc[1,'b']=np.nan

In [89]:
print(df1)
df2

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [90]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [91]:
df1.add(df2,fill_value=0.)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [92]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [93]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [97]:
df1.reindex(columns = df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

산술 연산 메서드: add(radd), sub(rsub), div(rdiv), floordiv(rfloordiv),mul(rmul),pow(rpow)

In [100]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [101]:
arr - arr[0] # 배열 브로드캐스팅

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [122]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    columns = list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [123]:
series = frame.iloc[0]

In [124]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [125]:
series2 = pd.Series(np.arange(3),index = list('bef'))
series2

b    0
e    1
f    2
dtype: int32

In [126]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [127]:
series3 = frame['d']

In [131]:
frame.sub(series3, axis = 'index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

5.2.6 함수 적용과 매핑

In [25]:
import pandas as pd
import numpy as np

frame = pd.DataFrame(np.random.randn(4,3), columns=list('bcd'),index=['Utah','Ohio','Taxes','Oregon'])
frame

b         c         d
Utah    0.823048  0.515600 -0.889635
Ohio   -1.445265 -0.213409  0.124870
Taxes   1.033547 -0.691940 -0.349377
Oregon -0.256464 -0.221522  0.014813

In [3]:
np.abs(frame)

b         c         d
Utah    0.550493  0.665579  1.834749
Ohio    1.006448  0.433625  0.222951
Taxes   1.279994  0.164050  0.211864
Oregon  0.321154  0.756412  1.651469

In [28]:
f = lambda x: x.max() - x.min()

frame.apply(f)

b    2.478811
c    1.207539
d    1.014505
dtype: float64

In [6]:
frame.apply(f, axis='columns')

Utah      2.500327
Ohio      1.440073
Taxes     1.491859
Oregon    2.407881
dtype: float64

In [30]:
def f2(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

frame.apply(f2) #시리즈 반환가능

b        c         d
min -1.445265 -0.69194 -0.889635
max  1.033547  0.51560  0.124870

In [31]:
format = lambda x: '%.2f' %x #실수 소수점 둘째자리까지

frame.applymap(format)

b      c      d
Utah     0.82   0.52  -0.89
Ohio    -1.45  -0.21   0.12
Taxes    1.03  -0.69  -0.35
Oregon  -0.26  -0.22   0.01

5.2.7 정렬과 순위

In [32]:
obj = pd.Series(range(4),index=['d','a','c','b'])

obj.sort_index()

a    1
b    3
c    2
d    0
dtype: int64

In [33]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    columns = list('dacb'),
                    index = ['three','one'])

frame

d  a  c  b
three  0  1  2  3
one    4  5  6  7

In [34]:
frame.sort_index()

d  a  c  b
one    4  5  6  7
three  0  1  2  3

In [35]:
frame.sort_index(axis=1)

a  b  c  d
three  1  3  2  0
one    5  7  6  4

In [36]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  2  3  1
one    4  6  7  5

In [37]:
obj = pd.Series([4,7,-3,2])

obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [38]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])

obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [39]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [40]:
frame.sort_values(by='a')

b  a
0  4  0
2 -3  0
1  7  1
3  2  1

In [44]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [45]:
obj = pd.Series([7,-5,7,4,2,0,4])

obj.rank() #숫자가 작은게 1등, 동일 등수면 평균으로 나옴

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [46]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [48]:
obj.rank(ascending = False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [49]:
frame = pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})

frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [51]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

5.2.8 중복 색인

In [52]:
obj = pd.Series(range(5),index=['a','a','b','b','c'])

obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [53]:
obj.index.is_unique

False

In [54]:
obj['a']

a    0
a    1
dtype: int64

In [55]:
df = pd.DataFrame(np.random.randn(4,3), index = ['a','a','b','b'])

df

0         1         2
a  0.634753 -0.314129  0.594260
a -0.943832 -0.980789 -1.807600
b -0.254830 -0.788600  0.064552
b -0.677001 -0.103309 -0.458937

In [58]:
df.loc['b']

0         1         2
b -0.254830 -0.788600  0.064552
b -0.677001 -0.103309 -0.458937

5.3 기술 통계 계산과 요약

In [60]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[.75,-1.3]],index = ['a','b','c','d'],columns=['one','two'])

df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [61]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [62]:
df.sum(axis = 'columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [64]:
df.mean(axis=1, skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [65]:
df.idxmax()

one    b
two    d
dtype: object

In [66]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [67]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [68]:
obj = pd.Series(['a','a','b','c']*4)

obj.describe() #수치가 아니라도 됨

count     16
unique     3
top        a
freq       8
dtype: object

5.3.1 상관관계와 공분산

In [7]:
import pandas as pd
import pandas_datareader as web
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL','IBM','MSFT','GOOG']}
price = pd.DataFrame({ticker:data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker:data['Volume']
                      for ticker, data in all_data.items()})

In [9]:
returns = price.pct_change() #pct_change()는 각 주식의 퍼센트 변화율 계산

returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2020-01-17  0.011071  0.002392  0.005597  0.019763
2020-01-21 -0.006777  0.006218 -0.003591  0.002709
2020-01-22  0.003570  0.033915 -0.004805  0.001044
2020-01-23  0.004816 -0.007089  0.006156  0.000471
2020-01-24 -0.002882 -0.016169 -0.010077 -0.013413

In [11]:
returns['MSFT'].corr(returns['IBM']) #상관관계

0.48141443818362

In [12]:
returns['MSFT'].cov(returns['IBM']) #공분산

8.954367060738934e-05

In [13]:
returns.MSFT.corr(returns.IBM)

0.48141443818362

In [14]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.396653  0.572930  0.522816
IBM   0.396653  1.000000  0.481414  0.410264
MSFT  0.572930  0.481414  1.000000  0.662174
GOOG  0.522816  0.410264  0.662174  1.000000

In [15]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000241  0.000080  0.000128  0.000122
IBM   0.000080  0.000167  0.000090  0.000080
MSFT  0.000128  0.000090  0.000208  0.000144
GOOG  0.000122  0.000080  0.000144  0.000227

In [16]:
returns.corrwith(returns.IBM)

AAPL    0.396653
IBM     1.000000
MSFT    0.481414
GOOG    0.410264
dtype: float64

In [17]:
returns.corrwith(volume)

AAPL   -0.116738
IBM    -0.117213
MSFT   -0.038932
GOOG   -0.004867
dtype: float64

5.3.2 유일값, 값 세기, 멤버십

In [18]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])

uniques = obj.unique()

uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [19]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [20]:
pd.value_counts(obj.values, sort = False)

b    2
c    3
a    3
d    1
dtype: int64

In [21]:
mask = obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [22]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [24]:
to_match = pd.Series(['c','a','b','b','c','a'])

unique_vals = pd.Series(['c','b','a'])

pd.Index(unique_vals).get_indexer(to_match)


array([0, 2, 1, 1, 0, 2], dtype=int64)

In [25]:
data = pd.DataFrame({'Qu1':[1,3,4,3,4],
                    'Qu2':[2,3,1,2,3],
                    'Qu3':[1,5,2,4,4]})

data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [26]:
data.apply(pd.value_counts).fillna(0)

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0